/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package work.lclpnet.launcherlogic;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class LauncherLogicTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", LauncherLogic.test());
    }
}
